services:
  airflow:
    build: .
    image: airflow:2.10.3-xvfb
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: ["airflow", "standalone"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./GPT-InvestAR:/GPT-InvestAR
      - ./edgar-crawler/:/edgar-crawler/
